-- 코드를 입력하세요
WITH RENTAL_FEE AS (
    SELECT
        C.CAR_ID,
        C.CAR_TYPE,
        ROUND(C.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE / 100), 0) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE (START_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30')
        OR (END_DATE >= '2022-11-01' AND END_DATE <= '2022-11-30')
        OR (START_DATE < '2022-11-01' AND END_DATE > '2022-11-30')
    )
    AND (C.CAR_TYPE = '세단' OR C.CAR_TYPE = 'SUV')
    AND P.DURATION_TYPE LIKE '30%'
    AND C.DAILY_FEE * 30 >= 500000 AND C.DAILY_FEE * 30 < 2000000
)

SELECT *
FROM RENTAL_FEE
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;