-- 코드를 입력하세요
WITH CTE AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS MAX_F
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, RI.FAVORITES
FROM REST_INFO AS RI
LEFT JOIN CTE
ON RI.FOOD_TYPE = CTE.FOOD_TYPE
WHERE RI.FAVORITES = CTE.MAX_F
ORDER BY FOOD_TYPE DESC;