-- 코드를 입력하세요
WITH CTE AS (
    SELECT WRITER_ID AS USER_ID, COUNT(*) AS COUNT
    FROM USED_GOODS_BOARD 
    GROUP BY WRITER_ID
)
SELECT
    U.USER_ID,
    U.NICKNAME,
    CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS `전체주소`,
    CONCAT(SUBSTR(U.TLNO, 1, 3), '-', SUBSTR(U.TLNO, 4, 4), '-', SUBSTR(U.TLNO, 8, 4)) AS `전화번호`
FROM USED_GOODS_USER AS U
JOIN CTE
ON CTE.USER_ID = U.USER_ID
WHERE CTE.COUNT >= 3
ORDER BY USER_ID DESC