-- 코드를 입력하세요
WITH CTE AS (
    SELECT CAR_ID, AVG(DATEDIFF(END_DATE, START_DATE) + 1) AS AVERAGE_DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
)

SELECT CAR_ID, ROUND(AVERAGE_DURATION, 1) AS AVERAGE_DURATION
FROM CTE
WHERE AVERAGE_DURATION >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC;
