-- 코드를 작성해주세요
WITH CTE AS ( 
    SELECT FISH_TYPE, COUNT(FISH_TYPE) AS FISH_COUNT 
    FROM FISH_INFO 
    GROUP BY FISH_TYPE 
) 

SELECT 
    COUNT(FI.ID) AS FISH_COUNT, 
    FNI.FISH_NAME 
FROM FISH_NAME_INFO AS FNI 
JOIN FISH_INFO AS FI 
ON FNI.FISH_TYPE = FI.FISH_TYPE 
GROUP BY FNI.FISH_NAME
ORDER BY FISH_COUNT DESC;