-- 코드를 입력하세요
WITH CTE AS (
    SELECT 
        USER_ID,
        COUNT(*) OVER() AS TOTAL_USER
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)
SELECT 
    YEAR(S.SALES_DATE) AS YEAR,
    MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT S.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT S.USER_ID) / I.TOTAL_USER, 1) AS PURCHASED_RATIO
FROM CTE AS I
JOIN ONLINE_SALE AS S
ON I.USER_ID = S.USER_ID
GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
ORDER BY YEAR, MONTH