-- 코드를 입력하세요
WITH CTE AS (
    SELECT CAR_ID, 1 AS AV
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE '2022-10-16' >= START_DATE AND '2022-10-16' <= END_DATE
    GROUP BY CAR_ID
)

SELECT CRCRH.CAR_ID, IF(COUNT(CTE.AV) >= 1, "대여중", "대여 가능") AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
LEFT JOIN CTE ON CRCRH.CAR_ID = CTE.CAR_ID
GROUP BY CRCRH.CAR_ID
ORDER BY CRCRH.CAR_ID DESC;