-- 코드를 입력하세요
WITH HISTORY AS (
    SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
),
PLAN AS (
    SELECT 
        PLAN_ID, 
        CAR_TYPE, 
        REGEXP_REPLACE(DURATION_TYPE, '[^0-9]', '') AS DURATION_TYPE, 
        DISCOUNT_RATE / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
),
CTE AS (
    SELECT 
    H.HISTORY_ID,
    IF(H.DURATION >= P.DURATION_TYPE, C.DAILY_FEE * H.DURATION * (1 - P.DISCOUNT_RATE), C.DAILY_FEE * H.DURATION) AS FEE,
    P.DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN HISTORY AS H
    ON C.CAR_ID = H.CAR_ID
    JOIN PLAN AS P
    ON C.CAR_TYPE = P.CAR_TYPE
    WHERE C.CAR_TYPE = '트럭' 
)

SELECT HISTORY_ID, MIN(ROUND(FEE, 0)) AS FEE
FROM CTE
GROUP BY HISTORY_ID
ORDER BY FEE DESC, HISTORY_ID DESC

