-- 코드를 입력하세요
WITH RECURSIVE CTE AS (
    SELECT 0 AS HOUR
    
    UNION 
    
    SELECT HOUR + 1
    FROM CTE
    WHERE HOUR < 23
)

SELECT CTE.HOUR, COUNT(HOUR(AO.DATETIME)) AS COUNT
FROM ANIMAL_OUTS AS AO
RIGHT JOIN CTE ON HOUR(AO.DATETIME) = CTE.HOUR
GROUP BY CTE.HOUR
ORDER BY CTE.HOUR ASC;