-- 코드를 입력하세요
WITH CTE AS (
    SELECT UGU.USER_ID, SUM(UGB.PRICE) AS TOTAL_SALES
    FROM USED_GOODS_USER AS UGU
    JOIN USED_GOODS_BOARD AS UGB
    ON UGU.USER_ID = UGB.WRITER_ID
    WHERE UGB.STATUS = 'DONE'
    GROUP BY UGU.USER_ID
)

SELECT CTE.USER_ID, UGU.NICKNAME, CTE.TOTAL_SALES AS TOTAL_SALES
FROM USED_GOODS_USER AS UGU
RIGHT JOIN CTE 
ON UGU.USER_ID = CTE.USER_ID
WHERE CTE.TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES



