-- 코드를 작성해주세요
SELECT HE.EMP_NO, HE.EMP_NAME, 
IF(AVG(HG.SCORE) >= 96, 'S', IF(AVG(HG.SCORE) >= 90, 'A', IF(AVG(HG.SCORE) >= 80, 'B', 'C'))) AS GRADE,
IF(AVG(HG.SCORE) >= 96, HE.SAL * 20 / 100, IF(AVG(HG.SCORE) >= 90, HE.SAL * 15 / 100, IF(AVG(HG.SCORE) >= 80, HE.SAL * 10 / 100, 0))) AS BONUS
FROM HR_EMPLOYEES AS HE
JOIN HR_GRADE AS HG
ON HE.EMP_NO = HG.EMP_NO
GROUP BY HG.EMP_NO
ORDER BY HE.EMP_NO;