-- 코드를 입력하세요
WITH CTE AS (
    SELECT 
        P.MEMBER_NAME,
        R.MEMBER_ID,
        RANK() OVER(ORDER BY COUNT(R.MEMBER_ID) DESC) AS RNK
    FROM REST_REVIEW AS R
    JOIN MEMBER_PROFILE AS P
    ON R.MEMBER_ID = P.MEMBER_ID
    GROUP BY R.MEMBER_ID
)
SELECT 
    CTE.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW AS R
JOIN CTE
ON R.MEMBER_ID = CTE.MEMBER_ID
WHERE CTE.RNK = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT
