-- 코드를 작성해주세요
WITH CTE AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    CTE.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV,
    ID
FROM ECOLI_DATA AS E
JOIN CTE
ON YEAR(E.DIFFERENTIATION_DATE) = CTE.YEAR
ORDER BY YEAR, YEAR_DEV
