-- 코드를 작성해주세요
WITH CTE AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT CTE.SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES AS HE
JOIN CTE 
ON HE.EMP_NO = CTE.EMP_NO
WHERE CTE.SCORE = (SELECT MAX(SCORE) FROM CTE)