-- 코드를 입력하세요
WITH CTE AS (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
    GROUP BY CATEGORY
)

SELECT FP.CATEGORY, FP.PRICE AS MAX_PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT AS FP
LEFT JOIN CTE 
ON FP.CATEGORY = CTE.CATEGORY
WHERE FP.PRICE = CTE.MAX_PRICE
ORDER BY MAX_PRICE DESC;