-- 코드를 작성해주세요
WITH CTE AS (
    SELECT 
        FISH_TYPE, 
        COUNT(*) AS FISH_COUNT, 
        AVG(IF(LENGTH IS NOT NULL, LENGTH, 10)) AS AVG_LENGTH, 
        MAX(IF(LENGTH IS NOT NULL, LENGTH, 10)) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT FISH_COUNT, MAX_LENGTH, FISH_TYPE
FROM CTE
WHERE AVG_LENGTH >= 33
ORDER BY FISH_TYPE
