-- 코드를 작성해주세요
WITH SKILL AS (
     SELECT
        (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS FE,
        (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'Python') AS PY,
        (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME = 'C#') AS CS
), 
CTE AS (
    SELECT 
        CASE 
            WHEN S.FE & D.SKILL_CODE > 0 AND S.PY & D.SKILL_CODE > 0 THEN 'A'
            WHEN S.CS & D.SKILL_CODE > 0 THEN 'B'
            WHEN S.FE & D.SKILL_CODE > 0 THEN 'C'
        END AS GRADE,
        D.ID,
        D.EMAIL
    FROM DEVELOPERS AS D
    JOIN SKILL AS S
)

SELECT *
FROM CTE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID

